# Generated by Django 6.0.6 on 2026-06-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cocktail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descrizione', models.TextField()),
                ('immagine', models.ImageField(upload_to='cocktails')),
            ],
        ),
        migrations.CreateModel(
            name='PuntoVendita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('indirizzo', models.CharField(max_length=1024)),
                ('telefono', models.CharField(max_length=20)),
                ('capienza', models.IntegerField(blank=True, null=True)),
                ('è_un_bar', models.BooleanField(default=False)),
            ],
        ),
    ]
